### ISSUE TITLE
ansible not found under "new" after install. 

### ISSUE THREAD

**Issue by improvethings** [ansible/ansible-jupyter-kernel#33]
$ uname -srm
Linux 4.9.0-6-amd64 x86_64
$ cat /etc/issue
Debian GNU/Linux 9 \n \l
$ pip install ansible-kernel
Requirement already satisfied: ansible-kernel in ./anaconda3/lib/python3.6/site-packages (0.4.2)
Requirement already satisfied: ansible in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (2.6.1)
Requirement already satisfied: jupyter in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (1.0.0)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (5.4.5)
Requirement already satisfied: docopt in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (0.6.2)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (4.23.4)
Requirement already satisfied: PyYAML in ./anaconda3/lib/python3.6/site-packages (from ansible-kernel) (3.12)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from ansible->ansible-kernel) (39.1.0)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.6/site-packages (from ansible->ansible-kernel) (2.10)
Requirement already satisfied: cryptography in ./anaconda3/lib/python3.6/site-packages (from ansible->ansible-kernel) (2.2.2)
Requirement already satisfied: paramiko in ./anaconda3/lib/python3.6/site-packages (from ansible->ansible-kernel) (2.4.1)
Requirement already satisfied: notebook in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (5.5.0)
Requirement already satisfied: qtconsole in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (4.3.1)
Requirement already satisfied: jupyter-console in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (5.2.0)
Requirement already satisfied: nbconvert in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (5.3.1)
Requirement already satisfied: ipykernel in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (4.8.2)
Requirement already satisfied: ipywidgets in ./anaconda3/lib/python3.6/site-packages (from jupyter->ansible-kernel) (7.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.6/site-packages (from jinja2->ansible->ansible-kernel) (1.0)
Requirement already satisfied: idna>=2.1 in ./anaconda3/lib/python3.6/site-packages (from cryptography->ansible->ansible-kernel) (2.6)
Requirement already satisfied: asn1crypto>=0.21.0 in ./anaconda3/lib/python3.6/site-packages (from cryptography->ansible->ansible-kernel) (0.24.0)
Requirement already satisfied: six>=1.4.1 in ./anaconda3/lib/python3.6/site-packages (from cryptography->ansible->ansible-kernel) (1.11.0)
Requirement already satisfied: cffi>=1.7 in ./anaconda3/lib/python3.6/site-packages (from cryptography->ansible->ansible-kernel) (1.11.5)
Requirement already satisfied: pynacl>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from paramiko->ansible->ansible-kernel) (1.2.1)
Requirement already satisfied: pyasn1>=0.1.7 in ./anaconda3/lib/python3.6/site-packages (from paramiko->ansible->ansible-kernel) (0.4.3)
Requirement already satisfied: bcrypt>=3.1.3 in ./anaconda3/lib/python3.6/site-packages (from paramiko->ansible->ansible-kernel) (3.1.4)
Requirement already satisfied: ipython-genutils in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (0.2.0)
Requirement already satisfied: pyzmq>=17 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (17.0.0)
Requirement already satisfied: traitlets>=4.2.1 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (4.3.2)
Requirement already satisfied: Send2Trash in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (1.5.0)
Requirement already satisfied: nbformat in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (4.4.0)
Requirement already satisfied: jupyter-client>=5.2.0 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (5.2.3)
Requirement already satisfied: tornado>=4 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (5.0.2)
Requirement already satisfied: jupyter-core>=4.4.0 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (4.4.0)
Requirement already satisfied: terminado>=0.8.1 in ./anaconda3/lib/python3.6/site-packages (from notebook->jupyter->ansible-kernel) (0.8.1)
Requirement already satisfied: ipython in ./anaconda3/lib/python3.6/site-packages (from jupyter-console->jupyter->ansible-kernel) (6.4.0)
Requirement already satisfied: prompt_toolkit<2.0.0,>=1.0.0 in ./anaconda3/lib/python3.6/site-packages (from jupyter-console->jupyter->ansible-kernel) (1.0.15)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.6/site-packages (from jupyter-console->jupyter->ansible-kernel) (2.2.0)
Requirement already satisfied: mistune>=0.7.4 in ./anaconda3/lib/python3.6/site-packages (from nbconvert->jupyter->ansible-kernel) (0.8.3)
Requirement already satisfied: entrypoints>=0.2.2 in ./anaconda3/lib/python3.6/site-packages (from nbconvert->jupyter->ansible-kernel) (0.2.3)
Requirement already satisfied: bleach in ./anaconda3/lib/python3.6/site-packages (from nbconvert->jupyter->ansible-kernel) (2.1.3)
Requirement already satisfied: pandocfilters>=1.4.1 in ./anaconda3/lib/python3.6/site-packages (from nbconvert->jupyter->ansible-kernel) (1.4.2)
Requirement already satisfied: testpath in ./anaconda3/lib/python3.6/site-packages (from nbconvert->jupyter->ansible-kernel) (0.3.1)
Requirement already satisfied: widgetsnbextension~=3.2.0 in ./anaconda3/lib/python3.6/site-packages (from ipywidgets->jupyter->ansible-kernel) (3.2.1)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.6/site-packages (from cffi>=1.7->cryptography->ansible->ansible-kernel) (2.18)
Requirement already satisfied: decorator in ./anaconda3/lib/python3.6/site-packages (from traitlets>=4.2.1->notebook->jupyter->ansible-kernel) (4.3.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./anaconda3/lib/python3.6/site-packages (from nbformat->notebook->jupyter->ansible-kernel) (2.6.0)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda3/lib/python3.6/site-packages (from jupyter-client>=5.2.0->notebook->jupyter->ansible-kernel) (2.7.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./anaconda3/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->ansible-kernel) (4.5.0)
Requirement already satisfied: jedi>=0.10 in ./anaconda3/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->ansible-kernel) (0.12.0)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->ansible-kernel) (0.1.0)
Requirement already satisfied: simplegeneric>0.8 in ./anaconda3/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->ansible-kernel) (0.8.1)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.6/site-packages (from ipython->jupyter-console->jupyter->ansible-kernel) (0.7.4)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.6/site-packages (from prompt_toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter->ansible-kernel) (0.1.7)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in ./anaconda3/lib/python3.6/site-packages (from bleach->nbconvert->jupyter->ansible-kernel) (1.0.1)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython->jupyter-console->jupyter->ansible-kernel) (0.5.2)
Requirement already satisfied: parso>=0.2.0 in ./anaconda3/lib/python3.6/site-packages (from jedi>=0.10->ipython->jupyter-console->jupyter->ansible-kernel) (0.2.0)
Requirement already satisfied: webencodings in ./anaconda3/lib/python3.6/site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->jupyter->ansible-kernel) (0.5.1)

and when I run 
$ jupiter notebook
It opens a tab in my browser. In the top right under "New" I only see "Python3" under Notebook and and under other I see "textfile, folder, terminal" as the three options.

**Comment by benthomasson** [comment]
Thanks for the bug report!   Try running this: python -m ansible_kernel.install . Do you see it then?

**Comment by improvethings** [comment]
Yes, I see it now. Thanks!

**Comment by benthomasson** [comment]
I noticed a few Python 3 issues while recreating this.   Please upgrade with `pip install -U ansible_kernel`. You should get version 0.5.0.

**Comment by benthomasson** [comment]
Updating the README with these instructions should work for now.
