### ISSUE TITLE
No ansible export choices in jupyter lab

### ISSUE THREAD

**Issue by ShadowMitia** [ansible/ansible-jupyter-kernel#50]
**Describe the bug**
When running a jupyter notebook (with `jupyter notebook` command), there available ansible exports in File -> Download As.

When running jupyterlab (with `jupyter lab` command), the menu is called Exports, and doesn't contain ansible exports choices.

**To Reproduce**
1. Install jupyterlab and jupyter-kernel using pip3 (pip3 install jupyterlab ansible-kernel)
2 Launch jupyter lab
3. Open or create an ansible notebook
4. Go to File -> Export Notebook As
5. Menu has a missing "ansible playboook" export item

**Expected behavior**
In jupyterlab there should be an option to export notebook as ansible playbooks.

**Screenshots**

Expected behaviour in jupyter notebook:
![screenshot from 2018-07-25 09-50-28](https://user-images.githubusercontent.com/3752363/43186956-8a28a06a-8ff0-11e8-9da4-333d881a9732.png)

Missing menu item in jupyterlab:
![screenshot from 2018-07-25 09-50-43](https://user-images.githubusercontent.com/3752363/43187024-b5a3ab0e-8ff0-11e8-8604-1863a3a83936.png)

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 28)
 - Browser: Firefox 61.0.1
- Jupyter version: 4.4.0
- Jupyter lab version: 0.32.1
- Ansible-Kernel version: 0.6.0

**Comment by benthomasson** [comment]
To recreate this issue please include the versions of Jupyter Notebook, Jupyter Lab, and Ansible Kernel that you have installed.     Please also include the steps that you used to install Ansible Kernel.

**Comment by ShadowMitia** [comment]
@benthomasson I edited my message. Sorry about that.

**Comment by benthomasson** [comment]
It looks like the way that adding custom exporters changed in Jupyter Lab from Jupyter Notebook.    I'll look into supporting Jupyter Lab.

**Comment by benthomasson** [comment]
Your first screen shot is missing a few exporters.   Try running this command `python -m ansible_kernel.install --sys-prefix` to enable them

**Comment by benthomasson** [comment]
Unfortunately the list of exporters appears to be hardcoded in this version of Jupyter Lab.   I manually add the exporters on this branch: https://github.com/benthomasson/jupyterlab/tree/ansible_exporters

If you want to try this out run this:

```
git clone https://github.com/benthomasson/jupyterlab.git
cd jupyterlab
git checkout ansible_exporters
pip install -e .
jlpm install
jlpm run build
jlpm run build:core 
jupyter lab build 
jupyter lab --dev-mode
```

**Comment by ShadowMitia** [comment]
I tried testing your branch, but I think I have something wrong with my jupyter installation, when running `jupyter lab --dev-mode` it fails to launch with a `FileNotFoundError: [Errno 2] No such file or directory: '/home/dimitri/.local/lib/python3.6/site-packages/packages/theme-light-extension': '/home/dimitri/.local/lib/python3.6/site-packages/packages/theme-light-extension'`.

I'll just have to remember to test this kernel in the notebook in the meantime.

Thank you for the quick response! Hope they'll fix this harcoded exports list business soon.

**Comment by ShadowMitia** [comment]
You mean the one inside the cloned folder? I get this message: `Directory '.' is not installable. File 'setup.py' not found.`

**Comment by benthomasson** [comment]
Try the parent directory.  There should be a `setup.py` there.

**Comment by ShadowMitia** [comment]
I managed to make it work by using `pip3 install --user -e .` (I was using `sudo` before). 
Finally I can see the exports! 

Thanks!

**Comment by benthomasson** [comment]
I added a feature request for this in JupyterLab here: jupyterlab/jupyterlab#5015
