### ISSUE TITLE
Python variable not accessible in a Ansible task

### ISSUE THREAD

**Issue by jcpowermac** [ansible/ansible-jupyter-kernel#67]
**Describe the bug**
An output variable from python is unavailable in a debug action under a ansible task.

**To Reproduce**
```ansible
#python
x = 5
x
```

    5

```ansible
#task
debug:
    var: x
```

    TASK [debug] *******************************************************************
    ok: [localhost] => {
        "x": "VARIABLE IS NOT DEFINED!"
    }

**Expected behavior**
Variable should be defined.

**Comment by benthomasson** [comment]
This has not been implemented yet.   Thanks for submitting the issue.   I'll work on implementing this next.
