### ISSUE TITLE
Getting the output of tasks on multiple hosts

### ISSUE THREAD

**Issue by montaropdf** [ansible/ansible-jupyter-kernel#68]
**Describe the bug**
Tasks runs for all hosts of the group specified in directive hosts, but any python cells afterward only get the result of the execution on the last host to finish its execution for the task.

**To Reproduce**
1. Create a notebook with the ansible kernel
2. Fill the first cell with an ansible inventory listing more then 1 host
3. In the second cell initiate an ansible playbook
4. In the third cell define a task and add the register directive to retrieve the output from the execution
5. In the fourth cell create a python block that will print the content of the variable specified in the register directive

**Expected behavior**
Provide a way for python code to be executed each time a task is executed for a host or ensure that variables in register directives are lists that will accumulate the results of each task execution.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome 69.0.3497.100 (Official Build) (64-bit)

**Server (please complete the following information):**
 - OS: RHEL 7
 - Jupyter Notebook Version: 5.6.0

**Additional context**

**Comment by benthomasson** [comment]
Thanks for submitting this issue.    I am considering different ways that this could work.   I could create a dictionary in the python environment with the results of all the hosts keyed by host name.  Would that work for you?

**Comment by benthomasson** [comment]
The memory use is a good point.  I'll think about this a bit more.  Ansible already holds too much in memory.   I'll try not to make that worse.
