### ISSUE TITLE
In case of Python 3.6, register variable error occurs.

### ISSUE THREAD

**Issue by sky-joker** [ansible/ansible-jupyter-kernel#69]
**Describe the bug**

When Ansible Kernel 0.8.0 is running in Docker container, the following error occurred.(Ansible Kernel is running on Python3.6)
The same error does not occur in python2.

**To Reproduce**

```
# docker run -p 8888:8888 -d -it --name jupyter centos:centos7
# docker exec -it jupyter bash
# yum -y install epel-release
# yum -y install python36 python36-devel gcc
# curl https://bootstrap.pypa.io/get-pip.py | python36
# pip3 install jupyter jupyterlab
# pip3 install ansible ansible-kernel ipython
# python36 -m ansible_kernel.install
# jupyter lab --ip=0.0.0.0 --allow-root
```

**Screenshots**

![bug_to_reproduce_register_variable](https://user-images.githubusercontent.com/19516126/46247341-d975db00-c444-11e8-833e-c5f5d55b5f94.gif)

![register_variable_bug](https://user-images.githubusercontent.com/19516126/46247343-e1ce1600-c444-11e8-8ae3-354419dcf3fd.png)

**Desktop (please complete the following information):**

* OS: CentOS Linux release 7.5.1804 (Core) and Red Hat Enterprise Linux Server release 7.5 (Maipo)
* Browser chrome
* Version 69.0.3497.100
* Jupyter 4.4.0
* Jupyter lab 0.34.12

**Additional context**

I fixed the bug as follows.

```diff
--- before/kernel.py    2018-09-29 14:31:59.057127090 +0000
+++ after/kernel.py 2018-09-29 14:32:22.212129487 +0000
@@ -432,7 +432,7 @@

             if message_data.get('full_results', None) and self.registered_variable is not None:
                 logger.debug('full_results %s', type(message_data.get('full_results')))
-                self.shell.run_cell("{0} = json.loads('{1}')".format(self.registered_variable,
+                self.shell.run_cell("import json; {0} = json.loads('{1}')".format(self.registered_variable,
                                                                      message_data.get('full_results')))

             if message_data.get('results', None):
```

![fix_to_reproduce_register_variable](https://user-images.githubusercontent.com/19516126/46247350-f90d0380-c444-11e8-910e-30a5470b6ba7.gif)

thanks.

**Comment by benthomasson** [comment]
Please make a pull request with those changes.
