### ISSUE TITLE
Unable to retrieve file contents

### ISSUE THREAD

**Issue by ohlisa55** [ansible/ansible-jupyter-kernel#79]
I can use ansible localhost -m setup in jupyter notebook cell but I cannot use any module like
 debug: msg="Test". It shows messages under the below.

fatal: [localhost]: FAILED! => Unable to retrieve file contents
Could not find or access '/private/var/folders/x6/d0kxr33j18vcg53bb29jqjh40000gn/T/ansible_kernel_playbookhz0dr5by/project/next_task0.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

Playbook ended
Context lost!

Can anyone help?

**Comment by benthomasson** [comment]
Hello ohlisa55,

Thanks for submitting an issue.   If possible please attach the contents of the notebook with the problem to this issue. 

Thanks,

Ben

**Comment by ohlisa55** [comment]
<img width="1440" alt="2019-01-06 22 50 20" src="https://user-images.githubusercontent.com/40290237/50737043-26b5d580-1208-11e9-9f7b-50fb208fb744.png">
Thanks for replying this issue.

As you can see a picture, when I execute a debug module the first one was ok. After that I made error then trying debug module again that showed me different result from the first one. 
What's going on?

**Comment by benthomasson** [comment]
In cell #9 there is a syntax error that causes the underlying ansible playbook to halt.     Try adding two spaces in front of the `msg:` argument to debug.    How it works right now to restart the playbook context make and run a `#play` cell.      I was thinking about fixing this restart problem anyway.  So thanks for submitting this issue.   I work on that next.

**Comment by ohlisa55** [comment]
<img width="1440" alt="2019-01-07 22 35 20" src="https://user-images.githubusercontent.com/40290237/50771300-8e822400-12cd-11e9-827f-1180f4053e8d.png">

>In cell 9 there is a syntax error that causes the underlying ansible playbook to halt. 
I deliberately made this error because I thought any cells can't execute after error occured.
But as you can see this picture that works fine if add #play then add modules.
Thanks!!

**Comment by seaurching** [comment]
I have same issues
<img width="1217" alt="截屏2023-08-23 22 40 00" src="https://github.com/ansible/ansible-jupyter-kernel/assets/7349963/8f44ebce-51ae-4191-94a6-bf64ececc30b">
